import streamlit as st
import plotly.express as px
import plotly.graph_objects as go
import re
import logging
from synthetic_data import generate_synthetic_data

logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(name)s - %(levelname)s - %(message)s')
logger = logging.getLogger("App")

st.set_page_config(page_title="NAV Exception Dashboard", layout="wide", initial_sidebar_state="expanded")
logger.info("Initializing Streamlit Application")

# Extract the logic from reconciliation_skill.md
with open("e:\\Project\\reconciliation_skill.md", "r") as f:
    md_content = f.read()

code_match = re.search(r'```python(.*?)```', md_content, re.DOTALL)
if code_match:
    skill_code = code_match.group(1).strip()
    exec(skill_code, globals())
else:
    st.error("No Python code block found in reconciliation_skill.md")

st.title("NAV Exception Management - Reconciliation Skill")

import os
import pandas as pd

# Initialize state
if 'raw_data' not in st.session_state:
    data_path = "e:\\Project\\data\\exceptions.json"
    if os.path.exists(data_path):
        st.session_state.raw_data = pd.read_json(data_path)
        logger.info("Loaded synthetic data from data folder.")
    else:
        st.error("Data file not found! Please run synthetic_data.py to generate it.")
        st.stop()
    skill = ReconciliationSkill()
    st.session_state.processed_data = skill.process_exceptions(st.session_state.raw_data)

df = st.session_state.processed_data

# Check if we are in detailed view
if "exception_id" in st.query_params:
    selected_exception = st.query_params["exception_id"]
    if st.button("← Back to All Funds"):
        st.query_params.clear()
        st.rerun()
        
    st.title(f"Detailed View: {selected_exception}")
    matching_data = df[df['Exception ID'] == selected_exception]
    
    if len(matching_data) == 0:
        st.query_params.clear()
        st.rerun()
        
    exc_data = matching_data.iloc[0]
    
    st.markdown("---")
    col_d1, col_d2 = st.columns(2)
    with col_d1:
        st.info(f"**Root Cause:** {exc_data['Root Cause']}")
        st.warning(f"**Status:** {exc_data['Status']}")
        st.metric("Variance Impact", f"${exc_data['Variance (USD)']:,.2f}")
    with col_d2:
        st.error(f"**Possible Reason:** {exc_data['Possible Reason']}")
        st.success(f"**Resolution Recommendation:** {exc_data['Recommendation']}")
        st.metric("Fund Name", exc_data['Fund Name'])
        
    # Trend Chart
    st.subheader("Confidence Score Trend")
    trend_data = exc_data['Confidence Trend']
    fig_trend = go.Figure()
    fig_trend.add_trace(go.Scatter(x=[f"Day {i+1}" for i in range(5)], y=trend_data, mode='lines+markers', name='Confidence'))
    fig_trend.update_layout(title=f"Confidence Trend (Last 5 Days)", yaxis_title="ML Score", yaxis_range=[0, 1])
    st.plotly_chart(fig_trend, use_container_width=True)
    
    st.stop() # Do not render the rest of the page

# Sidebar Filters
st.sidebar.header("Filters")
selected_fund = st.sidebar.selectbox("Select Fund", ["All"] + list(df['Fund Name'].unique()))
selected_status = st.sidebar.selectbox("Status", ["All"] + list(df['Status'].unique()))

filtered_df = df.copy()
if selected_fund != "All":
    filtered_df = filtered_df[filtered_df['Fund Name'] == selected_fund]
if selected_status != "All":
    filtered_df = filtered_df[filtered_df['Status'] == selected_status]

# KPIs
st.subheader("NAV Funds Details")
col1, col2, col3, col4 = st.columns(4)
col1.metric("Total Exceptions", len(filtered_df))
col2.metric("Open / Escalated", len(filtered_df[filtered_df['Status'].isin(['Open', 'Escalated'])]))
col3.metric("Total Variance Impact", f"${filtered_df['Variance (USD)'].sum():,.2f}")
col4.metric("Avg Escalation Age", f"{filtered_df['Age of Escalation (Days)'].mean():.1f} Days")

st.markdown("---")

# Visualizations
col_chart1, col_chart2 = st.columns(2)

with col_chart1:
    st.subheader("Exceptions by Break Type")
    fig_pie = px.pie(filtered_df, names='Break Type', title="Break Types Distribution", hole=0.4)
    st.plotly_chart(fig_pie, use_container_width=True)

with col_chart2:
    st.subheader("Variance vs Confidence")
    fig_scatter = px.scatter(
        filtered_df, 
        x='Variance (USD)', 
        y='Confidence Score', 
        color='Status',
        hover_data=['Exception ID', 'Fund Name'],
        title="Impact vs ML Confidence"
    )
    st.plotly_chart(fig_scatter, use_container_width=True)

# Data Table
st.subheader("Exception Details (Generated by Reconciliation Skill)")

# Format dataframe for display
display_df = filtered_df[['Exception ID', 'Fund Name', 'Break Type', 'Variance (USD)', 'Confidence Score', 'Age of Escalation (Days)', 'Status', 'Recommendation']].copy()

# Add a Link column
display_df["Details Link"] = "/?exception_id=" + display_df["Exception ID"]

# Render table
st.dataframe(
    display_df,
    column_config={
        "Details Link": st.column_config.LinkColumn("Action", display_text="View Details"),
        "Variance (USD)": st.column_config.NumberColumn(format="$%d")
    },
    hide_index=True,
    use_container_width=True
)
